### ISSUE TITLE
error while loading shared libraries: libismrmrd.so.1.13

### ISSUE THREAD

**Issue by huchengMRI** [ismrmrd/siemens_to_ismrmrd#113] opened 2022-12-26 20:21 UTC
Hi,

I installed ismrmrd and siemens_to_ismrmrd successfully on Ubuntu 20.4, However, I got this error when running the command siemens_to_ismrmrrd related to libismrmrd.so.1.13: cannot open shared object file: no such file or directory. I checked that the file libismrmrd.so.1.13 is in /usr/local/lib/. I wonder how to fix this.
Thanks!

Hu

**Comment by huchengMRI** [comment] 2022-12-27 22:16
Actually the same command siemens_to_ismrmrd in the folder of /build doesn't have that error. However, it cannot handle the raw data from XA30.

**Comment by hansenms** [comment] 2022-12-27 22:47
You have two of things going on:
1. For the missing libraries, set your LD_LIBRARY_PATH to include wherever your libraries are installed.
2. Use the option to skip sync data for the XA30 files and see if that helps.

**Comment by huchengMRI** [comment] 2022-12-28 01:28
Thanks Michael! The first problem is resolved by setting LD_LIBRARY_PATH.
I used "siemens_to_ismrmrd --skipSyncData -f fmri.dat" but it still failed. The error was "Failed to find MEAS.sProtConsistencyInfo.tBaselineString/tMeasuredBaselineString".

**Comment by hansenms** [comment] 2022-12-28 01:38
Bit unclear what the context of the error is, but if it is during stylesheet evaluation, maybe use the NX style sheet? Use the debug switch to output the intermediary files and debug from there.

**Comment by huchengMRI** [comment] 2022-12-28 16:29
I'm sorry but I couldn't get any clue from the two intermediate files: config_buffer.xprot and xml_raw.xml. I can send you these two files or the raw data for test.
Thanks.

**Comment by hansenms** [comment] 2022-12-28 17:55
Can you try the NX style sheet instead.

**Comment by huchengMRI** [comment] 2022-12-29 15:38
I first extracted IsmrmrdParameterMap_Siemens_NX.xsl and then tried to add "-x IsmrmrdParameterMap_Siemens_NX.xsl" in the command. The output is almost the same except this line: Using parameter XSL: IsmrmrdParameterMap_Siemens_NX.xsl.

**Comment by huchengMRI** [comment] 2023-01-06 15:25
[meas_MID00029_FID06922_pulseq.zip](https://github.com/ismrmrd/siemens_to_ismrmrd/files/10361140/meas_MID00029_FID06922_pulseq.zip)
Dear Michael,
It's very strange that our raw data or dicom file do not have baseline information. I checked the old issues on this board, people have succeeded to some level in reading the raw data from XA software. So I uploaded the raw data file from our site. Could you test it on your computer? 
Thanks,

Hu

**Comment by hansenms** [comment] 2023-01-06 17:27
A quick look at this shows that there are some bits missing in your headers. Specifically, we use `IRIS/DERIVED/imageColumns` and `IRIS/DERIVED/imageLines` to set the reconstruction matrix size in the ISMRMRD header. Those fields are empty in your header:

```
        <ParamLong."ImageLines">{ }
        <ParamLong."ImageColumns">{ }
```

So you end up generating an ISMRMRD header that looks something like:

```xml
    <reconSpace>
      <matrixSize>
        <x/>
        <y/>
        <z>1</z>
      </matrixSize>
      <fieldOfView_mm>
        <x>200</x>
        <y>200</y>
        <z>200</z>
      </fieldOfView_mm>
    </reconSpace>
```

When we try to deserialize that header we get an error trying to convert empty strings to integers. If you run the converter in a debugger, you will see (in the stack trace) where this problem occurs. 

You can write out the intermediate header that is produced in this line https://github.com/ismrmrd/siemens_to_ismrmrd/blob/master/main.cpp#L832 to have a look for yourself.

I think the ISMRMRD library could be better behaved here and write out what the serialization problem actually is to make the debugging a bit easier, but I think in either case, the problem is in the data here. We need some kind of header fields to determine the recon matrix.

To hack your way through, you can make your own stylesheet that hard codes the values or gets them from some other header field. 

Hope this helps

**Comment by huchengMRI** [comment] 2023-01-08 16:24
Thank you so much for your insightful reply. Now I have a better understand of the stylesheet. I hard coded the value and the converter worked!!
I will contact Siemens about the problem with the raw data.  
I noticed that the <ParamLong."ImageLines"> and <ParamLong."ImageColumns"> have the correct values in the config buffer (the first section of the header). Perhaps I can modify the stylesheet to read these values from config buffer. IRIS/DERIVED/imageColumns are in the DICOM buffer. I don't quite get how these values (e.g., ParamLong."ImageLines") were read in the first place. The stylesheet only specifies siemens.IRIS.DERIVED..., there is no option to add buffer information. I wonder if I need to modify the main.cpp file. Could you give me a hint?

**Comment by hansenms** [comment] 2023-01-08 16:30
The conversion of the protocol buffers to ISMMRD header is a two step process:

1. Protocol buffer values are extracted into a temporary (raw) xml document.
2. A stylesheet is applied to render that raw XML document as the ISMRMRD header. 

You can change both of these processes.

If you would like to change which parameters are put into the raw xml document (and what they are called), you need to change the parameter map. You can see here (https://github.com/ismrmrd/siemens_to_ismrmrd/blob/master/parameter_maps/IsmrmrdParameterMap_Siemens.xml#L62) how the image columns is extracted. 

If you want to modify the rendering you change the stylesheet, which you have already done. 

I'm going to close this issue, since I think you have a path forward and the title doesn't really capture the "issue" if you will. If you have new problems, please open a new one.

**Closed by hansenms** 2023-01-08 16:30 UTC
